### ISSUE TITLE
Duplicated handles increase the total counter

### ISSUE THREAD

**Issue by albmar** [IyesGames/iyes_progress#10]
The following code also increases the total counter for already added handles which shouldn't be the case.

https://github.com/IyesGames/bevy_loading/blob/5981c76aa2f98b56d322d29b536617343015e91c/src/asset.rs#L29-L32

This should fix it:

```rust
pub fn add<T: Into<HandleId>>(&mut self, handle: T) { 
     if self.handles.insert(handle.into()) {
          self.total += 1;
     }
} 
```

**Comment by inodentry** [comment]
This has been fixed long ago. Forgot to close the issue.
