### ISSUE TITLE
iyes_progress v0.3.0 and iyes_loopless v0.6.0 not integrating

### ISSUE THREAD

**Issue by Semihazah** [IyesGames/iyes_progress#15]
Using iyes_progress to track asset loading in a loopless state. When I run my game, I get an error message:

> thread 'main' panicked at 'State Transiton Stage not found (assuming auto-added label)', cargo\registry\src\github.com-1ecc6299db9ec823\iyes_loopless-0.5.1\src\state.rs:240:18

Looking at the cargo.toml, it seems that iyes_progress is requiring an older version of iyes_loopless. Would it be possible to update iyes_progress to require v0.6.0 or at least v0.5.0 and above?

**Comment by Indy2222** [comment]
Solved by #14

**Comment by brandon-reinhart** [comment]
Friendly request to get #14 merged.
