### ISSUE TITLE
Crate name

### ISSUE THREAD

**Issue by NiklasEi** [IyesGames/iyes_progress#8]
Can we consider renaming this crate as long as it's not widely used yet? I find the name `bevy_loading` misleading, because loading is only one use case, while the functionality the crate offers is progress tracking in general. This can be applied to loading, but also to (terrain-) generation, connection, or simple task tracking.

How about `bevy_progress_tracking`?

**Comment by inodentry** [comment]
I've thought about it, yeah.

Hmm, how would such a rename even be handled gracefully?

I guess release a new version under the old name, that just produces a compiler error telling ppl about the rename (and also a readme pointing to the rename). And then continue to squat the old name until someone has a better use for it and reaches out to ask for it.

**Comment by NiklasEi** [comment]
That sounds reasonable to me, yes.

**Comment by inodentry** [comment]
Done! The crate has been renamed to `iyes_progress`.
